export const GlTextureTargetTypeEnum = Object.freeze({
	TEXTURE_2D: "TEXTURE_2D",
	TEXTURE_CUBE_MAP: "TEXTURE_CUBE_MAP",
	// webgl2
	TEXTURE_3D: "TEXTURE_3D",
	TEXTURE_2D_ARRAY: "TEXTURE_2D_ARRAY",
});

export const GlTexturePnameTypeEnum = Object.freeze({
	TEXTURE_MAG_FILTER: "TEXTURE_MAG_FILTER",
	TEXTURE_MIN_FILTER: "TEXTURE_MIN_FILTER",
	TEXTURE_WRAP_S: "TEXTURE_WRAP_S",
	TEXTURE_WRAP_T: "TEXTURE_WRAP_T",
	TEXTURE_BASE_LEVEL: "TEXTURE_BASE_LEVEL",
	TEXTURE_COMPARE_FUNC: "TEXTURE_COMPARE_FUNC",
	TEXTURE_COMPARE_MODE: "TEXTURE_COMPARE_MODE",
	TEXTURE_MAX_LEVEL: "TEXTURE_MAX_LEVEL",
	TEXTURE_MAX_LOD: "TEXTURE_MAX_LOD",
	TEXTURE_MIN_LOD: "TEXTURE_MIN_LOD",
	TEXTURE_WRAP_R: "TEXTURE_WRAP_R",
});

export const GlTextureParamTypeEnum = Object.freeze({
	// TEXTURE_MAG_FILTER, TEXTURE_MIN_FILTER
	LINEAR: "LINEAR",
	NEAREST: "NEAREST",
	// TEXTURE_MIN_FILTER
	NEAREST_MIPMAP_NEAREST: "NEAREST_MIPMAP_NEAREST",
	LINEAR_MIPMAP_NEAREST: "LINEAR_MIPMAP_NEAREST",
	NEAREST_MIPMAP_LINEAR: "NEAREST_MIPMAP_LINEAR",
	LINEAR_MIPMAP_LINEAR: "LINEAR_MIPMAP_LINEAR",
	// TEXTURE_WRAP_S, TEXTURE_WRAP_T, TEXTURE_WRAP_R
	REPEAT: "REPEAT",
	CLAMP_TO_EDGE: "CLAMP_TO_EDGE",
	MIRRORED_REPEAT: "MIRRORED_REPEAT",
	// TEXTURE_COMPARE_FUNC
	LEQUAL: "LEQUAL",
	GEQUAL: "GEQUAL",
	LESS: "LESS",
	GREATER: "GREATER",
	EQUAL: "EQUAL",
	NOTEQUAL: "NOTEQUAL",
	ALWAYS: "ALWAYS",
	NEVER: "NEVER",
	// TEXTURE_COMPARE_MODE
	NONE: "NONE",
	COMPARE_REF_TO_TEXTURE: "COMPARE_REF_TO_TEXTURE",
});

/** @type {Record<number, CanvasEngineType.TextureUnitName>} */
export const GlTextureImageUnitsEnum = Object.freeze({
	0: "TEXTURE0",
	1: "TEXTURE1",
	2: "TEXTURE2",
	3: "TEXTURE3",
	4: "TEXTURE4",
	5: "TEXTURE5",
	6: "TEXTURE6",
	7: "TEXTURE7",
	8: "TEXTURE8",
	9: "TEXTURE9",
	10: "TEXTURE10",
	11: "TEXTURE11",
	12: "TEXTURE12",
	13: "TEXTURE13",
	14: "TEXTURE14",
	15: "TEXTURE15",
	16: "TEXTURE16",
	17: "TEXTURE17",
	18: "TEXTURE18",
	19: "TEXTURE19",
	20: "TEXTURE20",
	21: "TEXTURE21",
	22: "TEXTURE22",
	23: "TEXTURE23",
	24: "TEXTURE24",
	25: "TEXTURE25",
	26: "TEXTURE26",
	27: "TEXTURE27",
	28: "TEXTURE28",
	29: "TEXTURE29",
	30: "TEXTURE30",
	31: "TEXTURE31",
});
